services:
  # 開発用サービス
  dev:
    build:
      context: .
      # Dockerfileの'development'ステージまでを実行
      target: development
      args:
        EXCHANGERATE_API_KEY: ${EXCHANGERATE_API_KEY}
    ports:
      - '3000:3000'
    volumes:
      # ホットリロードのためにソースコードを同期
      - .:/app
    env_file:
      - .env

  # 本番用サービス
  prod:
    build:
      context: .
      # Dockerfileの'production'ステージまでを実行
      target: production
      args:
        EXCHANGERATE_API_KEY: ${EXCHANGERATE_API_KEY}
    ports:
      - '3000:3000'
    env_file:
      - .env
    # 本番ではホットリロードは不要なのでvolumesは設定しない
