services:
  # 開発用サービス
  dev:
    build:
      context: .
      # Dockerfileの'development'ステージまでを実行
      target: development
      secrets:
        - exchangerate_api_key
    ports:
      - '3000:3000'
    volumes:
      # ホットリロードのためにソースコードを同期
      - .:/app
    env_file:
      - .env
    secrets:
      - exchangerate_api_key

  # 本番用サービス
  prod:
    build:
      context: .
      # Dockerfileの'production'ステージまでを実行
      target: production
      secrets:
        - exchangerate_api_key
    ports:
      - '3000:3000'
    env_file:
      - .env
    secrets:
      - exchangerate_api_key
    # 本番ではホットリロードは不要なのでvolumesは設定しない

# Docker Secretsの定義
secrets:
  exchangerate_api_key:
    file: ./secrets/exchangerate_api_key.txt
