services:
  # 開発用サービス
  dev:
    build:
      context: .
      # Dockerfileの'development'ステージまでを実行
      target: development
    ports:
      - '3000:3000'
    volumes:
      # ホットリロードのためにソースコードを同期
      - .:/app

  # 本番用サービス
  prod:
    build:
      context: .
      # Dockerfileの'production'ステージまでを実行
      target: production
    ports:
      - '3000:3000'
    # 本番ではホットリロードは不要なのでvolumesは設定しない
